export const IMAGE_PLACEHOLDERS = {
  "/about/basketball-court.jpg": {
    "blurDataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAcAAAAKCAIAAAD3rtNaAAAACXBIWXMAAAsTAAALEwEAmpwYAAAA50lEQVQImQHcACP/AHCNu3SPuX2VvISZvoygwpGkxJeqyAB/mr6Jn8SUp8edrsqls82quM+tuc8AlKjIn7HKqrnQtsLUwMjWx83ayM7bAKe2y7S/0cLK1tDU29nc4N/g5OPi5ADIzdfX2N3k4+Py7ur9+fL//Pb/+vQAhIF+lJSTwr2zxMC3i42Ourax7N/QAAIDAAwPDiMnKCsvMhQbIhkeIhwcGgAhKSodIyQZHB0qLzElKi8OEhIZHCAALUA9PD8/REFBSUlIQkJHIyguIiQmABkpKBoiIh8oJh8mJR0lIyIwMSgzPkvSam+Ww/DEAAAAAElFTkSuQmCC",
    "width": 682,
    "height": 1024
  },
  "/about/golden-gate.jpg": {
    "blurDataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAHCAIAAAC+zks0AAAACXBIWXMAAAsTAAALEwEAmpwYAAAA5ElEQVQImQHZACb/AJSpsa66u7TAwKO2vZGruIGhsnaYrWaMpViAmkhzjQDByMPs6d7u7eXP1M+xwMWbtL6LqbZ7nq9tlKVehpoA5OXX///6///96+vey9LOtsfHqr7Anra7j62zgKCmANjQs/Tt1/z35vnx2+7p0tjUwMPEsqetnZCYjYCKgAAvKxpIPy1UTDdpYk+AemlybV9fXlJRVU1JUko9R0QAAwUABQcBEREKBwkDBQkAAQUAEA4EGBgOGh0XJCkmABoYEB4bEREOBAUDAAEDAAUFABIRChUUDAkHAAAAAPVYYrSzqqySAAAAAElFTkSuQmCC",
    "width": 1024,
    "height": 682
  },
  "/about/marine-drive.jpg": {
    "blurDataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAICAIAAABPmPnhAAAACXBIWXMAAAsTAAALEwEAmpwYAAABA0lEQVQImQH4AAf/AP/pr//rsv/qtP/qtv/muf/mvpiEelhTUpGCemNgYAD/+6P/8qP/7qbatonAn3++nH1NRUBXTkdIQj9SS0YA/+GJ3bV557Z51ahy6Ll4/siA4rJ5uZNup4dn0qd9AIxyVZx8Xa2GXa+GXbKJYY9yVXZiUIptVpd1WHZgTgA+LyNAMCU0Jx8zIxw4KR8qIBorIRgpIBohGhQeGBMAcVY+aE45Z0s3TDkoUzwuUDstNCcdJx4YJh4YJx8ZAG1SOWxROV9GMkQyJFA6KEs2JzMlGiMaEiMZEiAYEgBxVDdbQitNNyRONyRPOCRIMiExIhUgFQgaDwINAQB3JF4hrXHriwAAAABJRU5ErkJggg==",
    "width": 1024,
    "height": 768
  },
  "/about/yash.jpg": {
    "blurDataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAcAAAAKCAIAAAD3rtNaAAAACXBIWXMAAAsTAAALEwEAmpwYAAAA50lEQVQImQHcACP/AKHV/6bV/8Xi/+Lu/+r2/9Hn/7jd/wC95P/B5P/Y5/va7P/m8v/n8P/f7P8AvO3/vO3/wt7/0Ov/1+z/2er+2+z/ANX4/+P//8PU6ouKkeLw/+Py/9rr/gDj8P/w+/+9ws6KZlfu9v/i8/9/hJAAm7LLm62/dH6TVFRvjJm3tcjYIiUoAF9iZoGKjyk3UycrTE5EXI2ZsU9TVQBnZ2dxcnYcHzEIDSUrJzdhb4Z1fIgAVlZZdXZ6PzxDAAIbGyZAjZ62b3mKAJOfqoyYphkeKgIJJ0BVfo2fuX+NouAahT5E4eloAAAAAElFTkSuQmCC",
    "width": 515,
    "height": 772
  },
  "/photography/disneyland-firework-show.jpg": {
    "blurDataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAHCAIAAAC+zks0AAAACXBIWXMAAAsTAAALEwEAmpwYAAAA5ElEQVQImQHZACb/ACgAAC0AAC8AADgAAMZjSsZmTFUADcVwdYgbJkUAAABNAACIPjd9RDhIBAC0ZEqrRDdqABPehInuiY+LKTMAo1JP23Vt5JOGeD0wiEExnT45dgAS7niD/+TijjgxAJ9aR9iUfeOnm3c9N7xoSv+ghqw7OctgXP/05bVpVwD2yKzco4yRX01bHhbskWf/rX7HV02DLSbirZ3/5tAAqnBT/8Smsl9FyXBP5oVg5XtYnUI0YBsSp2FP0I92AEUPAG08KXwzH/p6Uc1lTZIsIrY9KYAaCV0GAF8AAILbWRmWQJ/UAAAAAElFTkSuQmCC",
    "width": 2246,
    "height": 1496
  },
  "/photography/disneyland-ironman-show.jpg": {
    "blurDataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAHCAIAAAC+zks0AAAACXBIWXMAAAsTAAALEwEAmpwYAAAA2UlEQVQImWPg5pdkZGJiZGZlZGKBIWYGBiYoEhGVFRcVExcRlJIQlxQXl5MQU5KWUJGVVJOTVpQUYTDR1pxSEFyb4H1xee3u2ZXfj/b9f7Lq7Y7Wi/ML+jLdGXRUVUrDHeJ9PZb3lK6fXP7/4ar/b3acX9U8rTaxNTeUQUZa2Ujdwt8ljI9PoCorNyYgRV5WXUhQXF1B2UZfi8FYy2pSaffytvlZ4en/P/84vvJAW05LY0qxvqoqLzcng6CAqJWuha+Dd5R3TF58TqRnhLOZi6Oxg5iIBDMLKwDNJz4/lKc5qQAAAABJRU5ErkJggg==",
    "width": 2246,
    "height": 1495
  },
  "/photography/disneyland-junglebook-show.jpg": {
    "blurDataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAHCAIAAAC+zks0AAAACXBIWXMAAAsTAAALEwEAmpwYAAAA5ElEQVQImQHZACb/ADwkFDomGGVNPpuPipuGh5GGeYGFcVxSQJieOpx4LABMMhlaNyKFZEbPx7r/9///693LtJuJknViSieUXywATDMTYTsinouCr6aV2L2j//Pf5NnEfWhBZU0ojUk0AD0hDls1HZltVX5NMrlrKbaSYbmbgqV+T2tSLXlKOgA8GxFPJRSJUCNYLRKFPB+bVip6OxrFupVtaD5LNyUAKSAPU0EePDETJiYRXD4nbjIgKSQbMDIxHxIOMCwVAD4aDTw+HVNWGnRyI2BOJjY+MQEEBQMDAg8PDg8PCUASSeKvLG/aAAAAAElFTkSuQmCC",
    "width": 2246,
    "height": 1495
  },
  "/photography/hk-bakery.jpg": {
    "blurDataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAHCAIAAAC+zks0AAAACXBIWXMAAAsTAAALEwEAmpwYAAAA5ElEQVQImQHZACb/ACEnMGBlZFdYVnNtaZWRi6W0wZSVlLm5s8nCuVVBOAAyNTKorayOkoqDg31vXFGLamOPe2/FoZS9t7E8LCIAjYJgy62Ht4FhkFo8aSwOVAAAWw0AOQAAg2pQiHNZAEFAJp1xUoNIKn08JbN7UXIkAlINAEMfAOnElP3cqwCNeVR5VDhHIAM0DwBVKARIEQA3CwC0il3/3Krnx5YAW0gjeWhBnoZikXZROR4APB4AgV8417KA0a18xaBvAAAAAE9HNmFUOoV5WcKyjP323f/75+ffyN3RuPDfwpKmXBNIoLrJAAAAAElFTkSuQmCC",
    "width": 2245,
    "height": 1495
  },
  "/photography/hk-basketball-court.jpg": {
    "blurDataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAcAAAAKCAIAAAD3rtNaAAAACXBIWXMAAAsTAAALEwEAmpwYAAAA50lEQVQImQHcACP/AHCNu3SPuX6VvISbvY2gw5CkxJmqyQCAmsCKn8OUp8edrsqls82qts+tudAAlKjHnrHNq7rQtsLUwMjWx83ayc/bAKe2y7TA0sLK1tHV29rb4d/g5OPj5QDHzdfW2Nzj4uLw7ur/+vT//fb++fQAh4WCl5WUxL21x8K7i4+Pvbu28uTWAAIDAAsQDiUpKisvMhQbIRccIRwcGgAfKCkdIiQYGxwpLy8lKiwQEhQaHiAALUE9PEBAQkJBSUlIQUJHIicvIyQmABkpKBoiIiIpKCEoJh8mJCMwMiczPW4JasYzJ2bbAAAAAElFTkSuQmCC",
    "width": 1496,
    "height": 2245
  },
  "/photography/hk-coin-rings.jpg": {
    "blurDataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAHCAIAAAC+zks0AAAACXBIWXMAAAsTAAALEwEAmpwYAAAA5ElEQVQImQHZACb/AJCKgGJQRlhaWop4cHNLPoh0bqKmpk9JRWhpZoKOjgD/9u2Ab2l3Zl5dTUdlXFWMh36be2xXS0doSTlKS0oAv7a0cH1+opCHmYV+zbSutpiHkYB1YmxseGdhiYmGAKKAb6qOgI99eY6AdvbLudC5rqOHeHNycPPRx395dQBXPi1pPSgVAACOc2ikkYSHiIK3qZ6boqLXvrl1d3YAGA8EDg4FIw0AzKebcldNdGxo//bwiYeE6NLMhpSUAFYVACwYDA4QBxAAAIBpYH6GhnBtacPFw+7UzougoaXIY/nI81CWAAAAAElFTkSuQmCC",
    "width": 2245,
    "height": 1495
  },
  "/photography/hk-diptyque-store.jpg": {
    "blurDataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAHCAIAAAC+zks0AAAACXBIWXMAAAsTAAALEwEAmpwYAAAA5ElEQVQImQHZACb/AJyEZH1gR7WrpolyX+nj37axrZ+bhmBqV0NGM1paSQCYhWqZfmKmm46LfGrYzsPo4+OtqZ2NjXaAgm9tcV4AzMS68uLM69q4rKOGsqOFwq2Yva+UpJiEl4t5j4VzAFxVY8OzqNzEoyQdGz07QzgoGottT9jDo5SGdnJmUgDm1bv/+tmKdV8GBAkbIzMPBAE6Hg++o4b/9t/WxrEA/+7Q//fSim1SclpCZVA7eF1CbFA4mX5f8d/F69zLAP/61//vzf/ox/Xbt+LHo9S6ltO5lN/Lr+DSwfbq2q/DeyTeoCFEAAAAAElFTkSuQmCC",
    "width": 2246,
    "height": 1495
  },
  "/photography/hk-flowershop.jpg": {
    "blurDataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAHCAIAAAC+zks0AAAACXBIWXMAAAsTAAALEwEAmpwYAAAA5ElEQVQImQHZACb/APDGupBuU2VuR1RcGExkR1toPnhkNUEkOTOzoT/JpgCTUjiJRCRbXixBPh40SkhDSjtPNhwqLzMWink5vqYAaFZRYllcrZ2jeFJwZ01LlHuBWEVfOUNaL0FGXWiAAGM2T7KTd5WFiFIwUFEcIrtxjIJn1VNGvoA9goVriQBPN1B1XEo6Jj0oGDE+IkRWKk5ULXgjEGZJOXljWm0AZFNjemWj987//+z/+rb70ZLQUA8ogS1pi2SRAAcAAEMyT6F25K2N3Yh2nsp8st6Qzbt6umcZSZ9zoUEpRV6IVooBeYRIAAAAAElFTkSuQmCC",
    "width": 2245,
    "height": 1496
  },
  "/photography/hk-foodmart.jpg": {
    "blurDataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAHCAIAAAC+zks0AAAACXBIWXMAAAsTAAALEwEAmpwYAAAA5ElEQVQImQHZACb/AIB8an1PLUETADwdBTgnGFI5I18qGh0AABoAABwXFgBpVVFDNzRVQkJtSiF2VCCLbTWKWiR3LxdnLBU9KiYAXE07MyAdXDgki1Umd00Oi1kTlkoweT0lYigbUSQjAE88NGw/K3ZKM6Z7WYNfKp9fKoYjGVAWE1EcDXAxHACmjXPepHOadU20koGxi3fRjlitaz5lRTI8GxBXLyAAy35dkWJC26Nm/+bN/+LX/7ed/+iThHVoKB84OigrAFQuALJ+ONWScNJzedRqa71oX9S/g5WLegIROjMnLHObSn3XA8WvAAAAAElFTkSuQmCC",
    "width": 2246,
    "height": 1496
  },
  "/photography/hk-halfway-coffee.jpg": {
    "blurDataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAcAAAAKCAIAAAD3rtNaAAAACXBIWXMAAAsTAAALEwEAmpwYAAAA50lEQVQImQHcACP/AHji74aqruDYzLKqmLKwpsHCwb7AwQC1wL7W6Oro49f//e/q5dHa2M/Qz8oALS4vQURFYmJgs7S07/Hry8rD+fn2AE9VUzM2NSguLigtLmFjYouOjeLk4AC/xLOxtaeFjImHko2Ok45QUVFxcGwAwMW7wMi8ucjAv87Lrr25TVFSa21qAEVCO1NTSWJkXHN4cnJ6d0JERYyOjgAhGxQhHBJIOiljVUIuKiMuLSmRkY0ATj0wVkItdmBHnYxzSUlBBAMDBQYDAFxJOGZMNWZSO5OEclRYUR0mEgoLCgXnZnpwuaM1AAAAAElFTkSuQmCC",
    "width": 1496,
    "height": 2246
  },
  "/photography/hk-hotel-peninsula.jpg": {
    "blurDataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAHCAIAAAC+zks0AAAACXBIWXMAAAsTAAALEwEAmpwYAAAA5ElEQVQImQHZACb/AJWBXnBfSCQkKhYWGRAQFTM0NzxETzQ4RTw8P4BwUQBcUTzpy5irmHmAc11YT0JQSUE+SF1DTF+fjXBwY1AAUUQtkH1cmINin41ts59/tJ1/l41+taSGjnpWTUM4AFtMM8GtgqqWcZuHaHpvWHxvWJF/Xp2HX5R9WLmfcgAlHROIeF3WwJb54bDu2Krgy6Pjyp/o0J7/97vIsoQAIRkRHhMLMSgbRzopZ1Y8cl1BblxCX1Q9SD0tDAoFAAMCAB4aESkjGR4ZESAZERoTDhoTDg4KBBMPBwoHAN14TldSc/gtAAAAAElFTkSuQmCC",
    "width": 2246,
    "height": 1496
  },
  "/photography/hk-jail-lobby.jpg": {
    "blurDataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAcAAAAKCAIAAAD3rtNaAAAACXBIWXMAAAsTAAALEwEAmpwYAAAA50lEQVQImQHcACP/ABIXHRYgKzs3MU9AKTIvKQACAgMEBAAZKDsrMTlVRi5VRS1RRzYYGRcNERMAJkBgUEUyXEswYFRCX1I8Rj0sExkeADlcg1xNLnRkTINsS3JkTWBVPh8lKwBHcJl2Zkebg1yth1SSgWBtY08kKzMAT3efm4RXq5VqgWhBjYBXVFE5LDQ7AFV3mJaAVaqUa6qTZnpwSUNCLC80OgBecodOPBvLrXv/+q6Jckk8NiQzNzkATVZgv59o/dqa/NaRxaBlX0wxJSkoAC80Oo96UrGSYaqLWJZ4R1xJKg4RERsFR5ABGiMsAAAAAElFTkSuQmCC",
    "width": 1495,
    "height": 2245
  },
  "/photography/hk-madame-tussads.jpg": {
    "blurDataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAHCAIAAAC+zks0AAAACXBIWXMAAAsTAAALEwEAmpwYAAAA5ElEQVQImQHZACb/AC0BAGwFBZARCb1IJ/KJYP94Y+JqSqtPNn0uIEoYEgBkHhi/IA7OMyemYFu7gHTUk4Pxn4v6mHjzhVbUVjcAfhQPziQQ/1RBsVVMSDgyPkI/NkE/p2ZfbTwsLSolAIIMCL8gDvBLO+YvJCcAAB8aFhoYGqdGPkkYDgAEBACLDwmzHA3eTz3nLyQvAAYEEQ8eGByXNjNwJiA4IiIAiQ4InxYK1FNB5WRUk2NaJSMeEA8VjDg1fjcsZTs0AF8eG7tpVPqzjf/wxaWAbAUGBxYWG382MoYoGmouIpmGRIGi0V/vAAAAAElFTkSuQmCC",
    "width": 2246,
    "height": 1496
  },
  "/photography/hk-nice-car.jpg": {
    "blurDataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAHCAIAAAC+zks0AAAACXBIWXMAAAsTAAALEwEAmpwYAAAA5ElEQVQImQHZACb/ACUlI2lbY3pydsPEut7d1ZCCfmNocIWDfeDGqouGgAAtLShZWVaRkZCdkZGUi4xiXFltbmi7sqz/+/ZRU1MAenJml5CExsK2gn97UlRSFRcVAwAAZ2Rerq6qj4NzANW5pPPYxcWvmUhHPTw8NxoYEy0oICYgF0pHQMSxlACijHqynYqfinZNPyY9MB8cFg0ZEwchGAhJQTJuYk0AjXdknYZyg21YZEowUTwhPSoURC8XXEs0W1BCHxgPAI54Y4x4ZGtfTmZaS29bRXdiTHliSmxdSlRKPCIcFetzVDYAyb3MAAAAAElFTkSuQmCC",
    "width": 2246,
    "height": 1495
  },
  "/photography/hk-porsche.jpg": {
    "blurDataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAHCAIAAAC+zks0AAAACXBIWXMAAAsTAAALEwEAmpwYAAAA4klEQVQImWOYPG3mp///G5umFOTXGpvbaipJGanwpSWGO5grcjIzMFg6uCVl56dFJofHZ/IJCYkK88WlZoQF+mir8Hv7uDKkZjcHxZQ6GBinZmYqKyswsjJraWuH2RhYCAn6+LgxWFh4WdkHhgWH5aamBJprlaXGxoSHKggzVETaVia4MwTFpkQnZ7n7+WloagoxMZiamSsqKnAwMEQ5qBdHODD0zF4wf9XK/t7a1AR/G1NNbydjDxsDE3VpMxVxK11FhtKacgcnp9LitNQYr1BXs/IU38oUX19LDXM1aTV5MQCRDDypJbxJegAAAABJRU5ErkJggg==",
    "width": 2246,
    "height": 1495
  },
  "/photography/hk-road-board.jpg": {
    "blurDataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAHCAIAAAC+zks0AAAACXBIWXMAAAsTAAALEwEAmpwYAAAA1UlEQVQImWO49/c/P5+omJi4GAKIysqpi4iICgryM7CwiiopqauoqElISEpKSkpISIhLiEtIKggKCvHz8TAwMDAICAiIigjz83GJCAuCGTx8fHxiYmJ8fLwMbRPm+YQkVjTPrWxbHBaXaWFjn5pTZG1rLyUlw8XFydAz43RF47aKhgNT5j2evep+QdWcVTs+h8QUyCsosbGxMXCwc3Owc9ha29pa2oiLi1uZm0mKS8hKg4CAgACDpISYqIhAQkJ6YW6hupqqgICAopxsdUashISEsLAwACzRLCuWt1HlAAAAAElFTkSuQmCC",
    "width": 2246,
    "height": 1496
  },
  "/photography/hk-road.jpg": {
    "blurDataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAHCAIAAAC+zks0AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAz0lEQVQImRXLu07DMBQAUIvg2mlqXz/iOLmxXbVqcYB0KBEIAUVCYu+PMFdiZWLhaxkYQZz9kO+f36/3z7ur7Zg32DZWSynKak4ZO6O0IMfj2+n0sU5xs14hYkTfY9c41zkFghHOKEiBzuzHyxhiSiGGYK09DBgcEM7ZjBZGy4fD03T/eDPtUkIQCwMV4+f/e0aLzqiXKd+O24vQ9l7XWjQanOAEKmZkmb18XdbPye68yo0KRtaiXKoF6a28bmGPZvAqt3podW+Fh7kRJVTsD9c9GQjC3K/bAAAAAElFTkSuQmCC",
    "width": 2246,
    "height": 1496
  },
  "/photography/hk-skyline.jpg": {
    "blurDataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAHCAIAAAC+zks0AAAACXBIWXMAAAsTAAALEwEAmpwYAAAA3klEQVQImWNQUVGCIH19XX19XVNTIwcHW3d357yCjIWLZjDIyEorKsiqa6jq6+taW5u5uzuHhgQmJcdOmdo7e/YEBkEBQRERYTk5GRUVJV09LQsrU2cnR3d3Zy9vd2trcwY+Pj4uDi4+Pj4RESFJSXEVFWVFBQV5eTlZOVkJSQkGfn4BaSlJLS0NPWMTDTXVwry8lKQkTS0dZWVlXSN9BmUVVWsLU3MzQ21dbT0dLU9vr7b66vsPn2XmZn77+opBUlJCUUFeV0tVSlKMjY1FT1vT0tzIy9vdwdkhKTYSAIcpL7PWelvRAAAAAElFTkSuQmCC",
    "width": 2246,
    "height": 1496
  },
  "/photography/hk-strawberries.jpg": {
    "blurDataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAHCAIAAAC+zks0AAAACXBIWXMAAAsTAAALEwEAmpwYAAAA5ElEQVQImQHZACb/AAAAAMKwwv/2/41ibSsAADwkI9KttO3AzdG/z82wxQCLUU53MTZxISWlQ0KsSUinTUrbioGqZGnXpar/6ugAlkhGaDIj1pRt/6WD/7WK2J574Y5lyF5KoVBNkmBTAL5dVrtXQdmQZPWUc/+jhf/Zpf/Wm/+0gK9jVu+IkgDGhHL/toTNV1H4mHf/snfsqn3/mmz/35y9d2C9aV8A7Jd5/9KU9Y13/59//6N9/62L/5yD/7KL4JB4pFtMAIImM4YnNZEyOZlASaNDT589QZ9BRZ0+RpU5QZdHS4dbdJwUJPJqAAAAAElFTkSuQmCC",
    "width": 2245,
    "height": 1496
  },
  "/photography/hk-sunflowers.jpg": {
    "blurDataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAHCAIAAAC+zks0AAAACXBIWXMAAAsTAAALEwEAmpwYAAAA5ElEQVQImQHZACb/AHVuJ52EPZ55G0VEAF1JOV1lMoGTSaqjar6kgorCgwCIYgWUbAmtdQ7blhzkqDqScCdyTQDfryTxzmWMsG8AdjsAY0YAkmkHj34OlHcQvnwSnVEDyncS/7kqlaBVAC0wFEE6GLJRBq5SBeaCGHIkAJQ6AA8AAD0iAIV3CgAvNzeDVRGwSAROHgDFZA22WAimVAVZKABoSwFlXDAAAA8cKSwcmksCcVInNzUkfFcoSjcTSjwmloNdprWtAAAKFQAOGgE2MDVVSEM9MUBFNyUtGHhzYtzHxfz9/+K7SLOB3BpZAAAAAElFTkSuQmCC",
    "width": 2246,
    "height": 1496
  },
  "/photography/hk-workshop-items.jpg": {
    "blurDataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAHCAIAAAC+zks0AAAACXBIWXMAAAsTAAALEwEAmpwYAAAA5ElEQVQImQHZACb/AAIUI5+bnMWyqYJfPXhcQMC9t2pXShUAAGI7K1owHgAWIS0qAAB+VEmXeVq2i3HJoYynbVJ9KhJ2SjI8HgYAOztARgUAoWdVyKSZ+8+v56+V0Y5tu2A3jGFFXEw4AGddT5SQcsCplf/v2719bL5MSenAo+bbrfrSpv/bowCNZUSdfGK0imvSn4PXm4W0al3+2bn42q7vyZ30z5wAzJhr3K6LpH1jrmVKjm5cd19R582yqpqBtaSKtcy+AEMMAIthRLSbgLuPdX5vYIRwYPXVtKCSd9rDpOvUwIr+bUUWuj/WAAAAAElFTkSuQmCC",
    "width": 2246,
    "height": 1496
  },
  "/photography/hk-workshop.jpg": {
    "blurDataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAHCAIAAAC+zks0AAAACXBIWXMAAAsTAAALEwEAmpwYAAAA5ElEQVQImQHZACb/ABgcHXhtdaiGlkEjM7IwcHeV2nqbpKd3aqJ/gGFOSgAaHyEiFxlADxBfTEKqh3mfinlWQTR1NTSkb11vTj8ADhASOysilnNRqZFxd2VSNigePDg5n52bVVNHOjInAH1yZ3JVPTQjFCQRA0AmF2BPTJuGd5VzWSkrKQcLDAB4Z1llQiJdNBNsSzmphW2ymnV/Y0aCaldPTUcFBwcAi3hjf2NRlmIxxpNYyJtnm4Zll4ZxWEo+AAMEDA4MAJeHeJmHenhgUZ94RsKvlPz+99/l309PSgQFBQcIB07kS/SixhZrAAAAAElFTkSuQmCC",
    "width": 2245,
    "height": 1495
  },
  "/photography/kl-patronas-towers.jpg": {
    "blurDataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAHCAIAAAC+zks0AAAACXBIWXMAAAsTAAALEwEAmpwYAAAA5ElEQVQImQHZACb/ABMTExYWFiAgICgoKC0tLi0tMSYmKR0dIBMTFw0NFAATExMXGBcdHR05OTpXV1xRT1YzMTgeHiMQEBYPEBYACAgKHx4fQ0NDYGBj4eHk/Pz/d3d9RURHJygtDA0VADY4OFVWVWFiYLW2tNHU1sTGy5iZmFRUU0ZIRjk7PAAqLCohJCGiqaXCxcG3vL27v8Wgop+tsq0qLComJyQAICIhnaek3ebeo6ejYGdvT1ZfkpSU0djRnKWhICIgAGJpaNro44eOiIKGhg0QGgQIFFVZXKy0rbnAvX2Dfw79TYnrwvr7AAAAAElFTkSuQmCC",
    "width": 2246,
    "height": 1496
  },
  "/photography/kl-skyline-from-hotel.jpg": {
    "blurDataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAHCAIAAAC+zks0AAAACXBIWXMAAAsTAAALEwEAmpwYAAAA5ElEQVQImQHZACb/AAECAhYYGSQnKDM3ODs8Pj1AQ0dJS0pKTEpKSi8wMAAWGBcmKio6PD1FSEhFSElJTE1JTE9FSEo+QEErLC0AFBcYHCMnHiMoKjI3O0JESExOTFBTSlBTQEFDMDE1ACwvMmJpapafnnt9fVhdXFBVVVldYHd/g1FVVC4tLQCcnZuBhYGenplXVE5qZmC4ta3p5t+anJlZYGApKCUAiYiHYWJeUFROAAIASEZAVlBK7tvIWVROSUlHJCQjACkkHZeSh/P29QICAC0sJjw0KpuUiywsKBsXESMiHsohQU8adqITAAAAAElFTkSuQmCC",
    "width": 2245,
    "height": 1495
  },
  "/photography/sf-art-museum.jpg": {
    "blurDataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAHCAIAAAC+zks0AAAACXBIWXMAAAsTAAALEwEAmpwYAAAA5ElEQVQImQHZACb/AEm4/03E/1nL/2Td/3Ho/3bq/3zp/4Pp/4fq/4js/wBOyP9c1v9m3f9etO1ZjK6Cr8mQ2/+U8P+b9f+c9f8AXd7/XKjUSFxkOjk5QDcuYUczUkpDi5GRr///sf//AGnf/ytHSTMpCT4+Ozc0MGZUSEVBPmJIM7na5bn//wB20f8UGRYnJwwwJx88LC9BKR8mGhZXPC2PhoEwTFQAdsX1ExYTGxsBHxgNOCIoNBsVLBsQZEI4TTMzHCw7AFSIrQMDABYQADEyMS0ZGsDBu255fUAiGE0yMBQiJg5GXrE/obMUAAAAAElFTkSuQmCC",
    "width": 2246,
    "height": 1497
  },
  "/photography/sf-goldengate-bridge.jpg": {
    "blurDataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAHCAIAAAC+zks0AAAACXBIWXMAAAsTAAALEwEAmpwYAAAA5ElEQVQImQHZACb/AJWpsK66u7bAwKW3vZOpt4KhsnWYrWiOpleBm0d1kADCycPt6uDv7ubR1dGywMWbtL6Lq7d9n69ulKVfhpoA5OTX///6///97evey9PNt8bHqr/Cnri7kq6zgaGnANrQtPXt1/755vrw2u/o0tvYwsPDsKqtnZCYjICJfQAvKhpGPipTSzZnX0x9eWhwbFxZWU1NU0tIUUo/SEcABQUABQUBEREKCQsFCw0CBwkBFBQNHBsTHB0XJSwoABkYEB4bEREOBAUFAAEBAAUFABERCBQSCgsJAAAAABeaYv9zQ/HtAAAAAElFTkSuQmCC",
    "width": 2246,
    "height": 1497
  },
  "/photography/sf-people-at-art-museum.jpg": {
    "blurDataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAHCAIAAAC+zks0AAAACXBIWXMAAAsTAAALEwEAmpwYAAAA5ElEQVQImQHZACb/AMb8/8z+/9D//8n//8rz/KR6ZK99ZKh8a0UnGCclGwC5z8uSp6bAx8DO3tXn//+Zc2Klcly0hW1waWMzREoAUl1MOEUzcWBJmXhgtLSnr4dt2bON1LqaIiIfBAMAAAkNAQwOCTovJ2ZOQGFNPmhRSGxhUWBXThkYFQoKCAAvNUEwNTc0OzYwOisvOCkmNCcjLx4cIxwVFRYGBgUAO0JTKSwtHi0TFi4AFCwAFysIFikJHCwYEBoVBgoJACUqNykrOTQ1QCkxMRgjFwoaAwcZAAQYAAMYAAEUAdjKQ94/EehLAAAAAElFTkSuQmCC",
    "width": 2246,
    "height": 1498
  },
  "/photography/sf-town.jpg": {
    "blurDataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAHCAIAAAC+zks0AAAACXBIWXMAAAsTAAALEwEAmpwYAAAA5ElEQVQImQHZACb/AAQFBgAAAEtshJTU/4jE8YnF84TA7nev2niz4kFdbgAFBgYAAABFX22q5v+i2v6i3P+a0fWKu9xkh6IjKSkABgYHAAAAgJOY4P//0fX/0PH+uNfhaHh8GR0aDAwIAAQEAwYHB29uYIyIcWtwXJuXeoB4XC8xJxEUFAsLCgAAAAAtODx/i4t7iIpsh46Up6qSp69dbXQnKioMDg4AICotWHmMiK3Fg6e+fKO5d5uvcpWsTWp5ICstFBkZACMuNC5FUi1DUi9IWy1HVx0sNyg+TjFQaCM8TxEdJV5nU6OzqWItAAAAAElFTkSuQmCC",
    "width": 2246,
    "height": 1498
  }
} as const;

export type ImagePlaceholderSrc = keyof typeof IMAGE_PLACEHOLDERS;
