const MUSIC_TRACK_ITEMS = [
  {
    id: "MUSIC_TRACK_LET_IT_HAPPEN",
    appleMusicId: "1440838060",
    title: "Let It Happen",
    artist: "Tame Impala",
  },
  {
    id: "MUSIC_TRACK_INSTANT_CRUSH",
    appleMusicId: "617154362",
    title: "Instant Crush",
    artist: "Daft Punk",
  },
  {
    id: "MUSIC_TRACK_DONT_WAIT_UP",
    appleMusicId: "1789425352",
    title: "Don't Wait Up",
    artist: "Midnight Generation",
  },
  {
    id: "MUSIC_TRACK_ONE_MANS_DREAM",
    appleMusicId: "255942465",
    title: "One Man's Dream",
    artist: "Yanni",
  },
  {
    id: "MUSIC_TRACK_THE_LESS_I_KNOW_THE_BETTER",
    appleMusicId: "1440838488",
    title: "The Less I Know the Better",
    artist: "Tame Impala",
  },
  {
    id: "MUSIC_TRACK_DIGITAL_LOVE",
    appleMusicId: "697195633",
    title: "Digital Love",
    artist: "Daft Punk",
  },
  {
    id: "MUSIC_TRACK_TROUBLE",
    appleMusicId: "1508709850",
    title: "Trouble",
    artist: "Midnight Generation",
  },
  {
    id: "MUSIC_TRACK_NIGHTINGALE",
    appleMusicId: "1439509525",
    title: "Nightingale",
    artist: "Yanni",
  },
  {
    id: "MUSIC_TRACK_BORDERLINE",
    appleMusicId: "1497230972",
    title: "Borderline",
    artist: "Tame Impala",
  },
  {
    id: "MUSIC_TRACK_SOMETHING_ABOUT_US",
    appleMusicId: "697195941",
    title: "Something About Us",
    artist: "Daft Punk",
  },
  {
    id: "MUSIC_TRACK_ENERGY",
    appleMusicId: "1797207887",
    title: "Energy",
    artist: "Midnight Generation",
  },
  {
    id: "MUSIC_TRACK_IN_THE_MIRROR",
    appleMusicId: "255942912",
    title: "In the Mirror",
    artist: "Yanni",
  },
  {
    id: "MUSIC_TRACK_ALMOST_A_WHISPER",
    appleMusicId: "302055657",
    title: "Almost a Whisper",
    artist: "Yanni",
  },
  {
    id: "MUSIC_TRACK_FACE_IN_THE_PHOTOGRAPH",
    appleMusicId: "268527144",
    title: "Face in the Photograph",
    artist: "Yanni",
  },
  {
    id: "MUSIC_TRACK_I_CANT_DO_WITHOUT_YOU",
    appleMusicId: "1530962995",
    title: "I Can't Do Without You",
    artist: "Midnight Generation",
  },
  {
    id: "MUSIC_TRACK_FEEL_IT",
    appleMusicId: "1816239876",
    title: "Feel It",
    artist: "Protoje",
  },
  {
    id: "MUSIC_TRACK_STANDING_ON_THE_SHORE",
    appleMusicId: "1449912308",
    title: "Standing on the Shore",
    artist: "Empire of the Sun",
  },
  {
    id: "MUSIC_TRACK_WALKING_ON_A_DREAM",
    appleMusicId: "1449912309",
    title: "Walking on a Dream",
    artist: "Empire of the Sun",
  },
  {
    id: "MUSIC_TRACK_LOST_IN_YESTERDAY",
    appleMusicId: "1497231163",
    title: "Lost in Yesterday",
    artist: "Tame Impala",
  },
  {
    id: "MUSIC_TRACK_ONE_MORE_TIME",
    appleMusicId: "697402070",
    title: "One More Time (Radio Edit)",
    artist: "Daft Punk",
  },
  {
    id: "MUSIC_TRACK_IN_THE_MORNING_LIGHT",
    appleMusicId: "255942308",
    title: "In the Morning Light",
    artist: "Yanni",
  },
  {
    id: "MUSIC_TRACK_NEVERENDER_EXTENDED",
    appleMusicId: "1767813008",
    title: "Neverender (Extended)",
    artist: "Justice & Tame Impala",
  },
  {
    id: "MUSIC_TRACK_TOUCH",
    appleMusicId: "617154364",
    title: "Touch (feat. Paul Williams)",
    artist: "Daft Punk",
  },
  {
    id: "MUSIC_TRACK_HORIZON",
    appleMusicId: "1673536455",
    title: "Horizon (Japan CD)",
    artist: "Daft Punk",
  },
  {
    id: "MUSIC_TRACK_WITHIN",
    appleMusicId: "617154361",
    title: "Within",
    artist: "Daft Punk",
  },
  {
    id: "MUSIC_TRACK_THE_RAIN_MUST_FALL",
    appleMusicId: "302055659",
    title: "The Rain Must Fall",
    artist: "Yanni",
  },
  {
    id: "MUSIC_TRACK_SANTORINI",
    appleMusicId: "258617158",
    title: "Santorini",
    artist: "Yanni",
  },
  {
    id: "MUSIC_TRACK_WITHIN_ATTRACTION",
    appleMusicId: "298322534",
    title: "Within Attraction",
    artist: "Yanni",
  },
  {
    id: "MUSIC_TRACK_LOVE_IS_ALL",
    appleMusicId: "1439509522",
    title: "Love Is All",
    artist: "Yanni",
  },
  {
    id: "MUSIC_TRACK_WALTZ_IN_7_8",
    appleMusicId: "1439509524",
    title: "Waltz in 7/8",
    artist: "Yanni",
  },
  {
    id: "MUSIC_TRACK_DANCE_WITH_A_STRANGER",
    appleMusicId: "327379858",
    title: "Dance with a Stranger",
    artist: "Yanni",
  },
  {
    id: "MUSIC_TRACK_FELITSA",
    appleMusicId: "255942931",
    title: "Felitsa",
    artist: "Yanni",
  },
  {
    id: "MUSIC_TRACK_THIRST_FOR_LIFE",
    appleMusicId: "1067977712",
    title: "Thirst for Life",
    artist: "Yanni",
  },
  {
    id: "MUSIC_TRACK_WHAT_YOU_GET",
    appleMusicId: "1067977715",
    title: "What You Get",
    artist: "Yanni",
  },
  {
    id: "MUSIC_TRACK_THE_KEEPER",
    appleMusicId: "1067977718",
    title: "The Keeper",
    artist: "Yanni",
  },
  {
    id: "MUSIC_TRACK_MARCHING_SEASON",
    appleMusicId: "327379583",
    title: "Marching Season",
    artist: "Yanni",
  },
  {
    id: "MUSIC_TRACK_DESIRE",
    appleMusicId: "298545853",
    title: "Desire",
    artist: "Yanni",
  },
  {
    id: "MUSIC_TRACK_INTO_THE_DEEP_BLUE",
    appleMusicId: "1488800267",
    title: "Into the Deep Blue",
    artist: "Yanni",
  },
  {
    id: "MUSIC_TRACK_FEEL_MY_NEEDS",
    appleMusicId: "1418096785",
    title: "Feel My Needs (Purple Disco Machine Extended Mix)",
    artist: "WEISS",
  },
  {
    id: "MUSIC_TRACK_VERDWAALD",
    appleMusicId: "1590908250",
    title: "Verdwaald",
    artist: "Didier Armeni",
  },
  {
    id: "MUSIC_TRACK_HOW_I_FEEL",
    appleMusicId: "1469514073",
    title: "How I Feel (feat. Hayley May)",
    artist: "Martin Ikin",
  },
  {
    id: "MUSIC_TRACK_11TH_DIMENSION",
    appleMusicId: "335804170",
    title: "11th Dimension",
    artist: "Julian Casablancas",
  },
  {
    id: "MUSIC_TRACK_TIME_TO_PRETEND",
    appleMusicId: "273519673",
    title: "Time to Pretend",
    artist: "MGMT",
  },
  {
    id: "MUSIC_TRACK_VOLUNTARY_EXILE",
    appleMusicId: "1540725578",
    title: "Voluntary Exile",
    artist: "Arc De Soleil",
  },
  {
    id: "MUSIC_TRACK_SIERRA",
    appleMusicId: "1753059922",
    title: "Sierra",
    artist: "George Bloomfield",
  },
  {
    id: "MUSIC_TRACK_DORADO_VALLEY",
    appleMusicId: "1632318115",
    title: "Dorado Valley",
    artist: "Hermanos Gutiérrez",
  },
  {
    id: "MUSIC_TRACK_CHAMELEON_SUNDAY",
    appleMusicId: "1462310232",
    title: "Chameleon Sunday",
    artist: "Arc De Soleil",
  },
  {
    id: "MUSIC_TRACK_LAST_DANCE",
    appleMusicId: "1705981611",
    title: "Last Dance",
    artist: "LEISURE",
  },
  {
    id: "MUSIC_TRACK_SOAK_MY_HEAD",
    appleMusicId: "1684767685",
    title: "Soak My Head",
    artist: "Meltt",
  },
  {
    id: "MUSIC_TRACK_SOUL_REBEL",
    appleMusicId: "691469395",
    title: "Soul Rebel",
    artist: "The Gladiators",
  },
  {
    id: "MUSIC_TRACK_TRAIN_TO_SKAVILLE",
    appleMusicId: "1436630174",
    title: "Train to Skaville",
    artist: "The Ethiopians",
  },
  {
    id: "MUSIC_TRACK_TRACK_AND_FIELD",
    appleMusicId: "1525340511",
    title: "Track & Field",
    artist: "Arc De Soleil",
  },
  {
    id: "MUSIC_TRACK_STARS",
    appleMusicId: "1616663079",
    title: "Stars",
    artist: "Brian Culbertson",
  },
  {
    id: "MUSIC_TRACK_EVERY_SINGLE_HEARTBEAT",
    appleMusicId: "1740514487",
    title: "Every Single Heartbeat",
    artist: "Maggie Reilly",
  },
  {
    id: "MUSIC_TRACK_ANYPLACE_ANYWHERE_ANYTIME",
    appleMusicId: "1523565857",
    title: "Anyplace, Anywhere, Anytime (Special 12\" Dance Mix)",
    artist: "Nena",
  },
  {
    id: "MUSIC_TRACK_THIS_IS_THE_LIFE",
    appleMusicId: "1442903044",
    title: "This Is the Life",
    artist: "Amy Macdonald",
  },
  {
    id: "MUSIC_TRACK_QUEEN_OF_RAIN",
    appleMusicId: "1590541908",
    title: "Queen of Rain (Demo)",
    artist: "Roxette",
  },
  {
    id: "MUSIC_TRACK_MAN_IN_THE_RAIN",
    appleMusicId: "79324409",
    title: "Man in the Rain",
    artist: "Mike Oldfield",
  },
  {
    id: "MUSIC_TRACK_MOONLIGHT_SHADOW_EMILY_LINGE",
    appleMusicId: "1879347094",
    title: "Moonlight Shadow",
    artist: "Emily Linge",
  },
  {
    id: "MUSIC_TRACK_LIFELINES",
    appleMusicId: "1474957342",
    title: "Lifelines",
    artist: "a-ha",
  },
  {
    id: "MUSIC_TRACK_EVERYTIME_WE_TOUCH",
    appleMusicId: "1649709685",
    title: "Everytime We Touch",
    artist: "Maggie Reilly",
  },
  {
    id: "MUSIC_TRACK_I_CAN_HEAR_YOUR_HEARTBEAT",
    appleMusicId: "208830374",
    title: "I Can Hear Your Heartbeat",
    artist: "Chris Rea",
  },
  {
    id: "MUSIC_TRACK_SELF_CONTROL",
    appleMusicId: "1522456568",
    title: "Self Control",
    artist: "Laura Branigan",
  },
  {
    id: "MUSIC_TRACK_THE_WAY_IT_IS",
    appleMusicId: "258517392",
    title: "The Way It Is",
    artist: "Bruce Hornsby & The Range",
  },
  {
    id: "MUSIC_TRACK_RESTLESS_HEART",
    appleMusicId: "1806612072",
    title: "Restless Heart",
    artist: "Sun City",
  },
  {
    id: "MUSIC_TRACK_MOONLIGHT_SHADOW",
    appleMusicId: "1442908890",
    title: "Moonlight Shadow",
    artist: "Mike Oldfield",
  },
  {
    id: "MUSIC_TRACK_INNOCENT",
    appleMusicId: "724410989",
    title: "Innocent",
    artist: "Mike Oldfield",
  },
  {
    id: "MUSIC_TRACK_HOLD_THE_LINE",
    appleMusicId: "198227598",
    title: "Hold the Line",
    artist: "Toto",
  },
  {
    id: "MUSIC_TRACK_BIG_LOG",
    appleMusicId: "254163493",
    title: "Big Log",
    artist: "Robert Plant",
  },
  {
    id: "MUSIC_TRACK_NO_REPLY",
    appleMusicId: "1836226729",
    title: "No Reply",
    artist: "Tame Impala",
  },
  {
    id: "MUSIC_TRACK_CRYING_AT_THE_DISCOTEQUE",
    appleMusicId: "273934015",
    title: "Crying at the Discoteque",
    artist: "Alcazar",
  },
  {
    id: "MUSIC_TRACK_EAT_YOU_ALIVE",
    appleMusicId: "1649392504",
    title: "Eat You Alive",
    artist: "Tokyo Tea Room",
  },
  {
    id: "MUSIC_TRACK_SHOOT_TO_THRILL",
    appleMusicId: "575998655",
    title: "Shoot to Thrill",
    artist: "AC/DC",
  },
  {
    id: "MUSIC_TRACK_ROCK_N_ROLL_DAMNATION",
    appleMusicId: "575998656",
    title: "Rock 'N' Roll Damnation",
    artist: "AC/DC",
  },
  {
    id: "MUSIC_TRACK_COLD_HEARTED_MAN",
    appleMusicId: "575998659",
    title: "Cold Hearted Man",
    artist: "AC/DC",
  },
  {
    id: "MUSIC_TRACK_BACK_IN_BLACK",
    appleMusicId: "575998660",
    title: "Back in Black",
    artist: "AC/DC",
  },
  {
    id: "MUSIC_TRACK_THUNDERSTRUCK",
    appleMusicId: "575998661",
    title: "Thunderstruck",
    artist: "AC/DC",
  },
  {
    id: "MUSIC_TRACK_IF_YOU_WANT_BLOOD",
    appleMusicId: "575998662",
    title: "If You Want Blood (You've Got It)",
    artist: "AC/DC",
  },
  {
    id: "MUSIC_TRACK_EVIL_WALKS",
    appleMusicId: "575998663",
    title: "Evil Walks",
    artist: "AC/DC",
  },
  {
    id: "MUSIC_TRACK_HAVE_A_DRINK_ON_ME",
    appleMusicId: "575998666",
    title: "Have a Drink on Me",
    artist: "AC/DC",
  },
  {
    id: "MUSIC_TRACK_LET_THERE_BE_ROCK",
    appleMusicId: "575998821",
    title: "Let There Be Rock",
    artist: "AC/DC",
  },
  {
    id: "MUSIC_TRACK_HIGHWAY_TO_HELL",
    appleMusicId: "575998831",
    title: "Highway to Hell",
    artist: "AC/DC",
  },
] as const;

export const MUSIC_TRACKS = [...MUSIC_TRACK_ITEMS].sort(
  (a, b) =>
    a.title.localeCompare(b.title, "en", { sensitivity: "base" }) ||
    a.artist.localeCompare(b.artist, "en", { sensitivity: "base" }),
);

export type MusicTrack = {
  id: string;
  title: string;
  artist: string;
  artworkUrl: string;
  largeArtworkUrl: string;
  previewUrl: string;
};
